Repository SSGINCFinal/show-ping-live, pull requests merged in 2025-03, with the labels that each got.

#24 Feat: 기본 채팅 구현
  build.gradle
  src/main/java/com/ssginc/showpinglive/config/JwtSecurityConfig.java
  src/main/java/com/ssginc/showpinglive/config/JwtTokenProvider.java
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketChatConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketConfig.java
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java
  src/main/java/com/ssginc/showpinglive/dto/object/ChatDto.java
  src/main/java/com/ssginc/showpinglive/dto/object/ForbiddenWord.java
  src/main/java/com/ssginc/showpinglive/handler/WebSocketChatHandler.java
  src/main/java/com/ssginc/showpinglive/handler/WebSocketHandler.java
  src/main/java/com/ssginc/showpinglive/jwt/JwtFilter.java
  src/main/java/com/ssginc/showpinglive/jwt/JwtUtil.java
  src/main/java/com/ssginc/showpinglive/repository/ChatRepository.java
  src/main/java/com/ssginc/showpinglive/repository/ChatRoomRepository.java
  src/main/java/com/ssginc/showpinglive/repository/ForbiddenWordRepository.java
  src/main/java/com/ssginc/showpinglive/service/ChatService.java
  src/main/java/com/ssginc/showpinglive/service/CustomUserDetailsService.java
  src/main/java/com/ssginc/showpinglive/service/KafkaConsumerService.java
  src/main/java/com/ssginc/showpinglive/service/KafkaProducerService.java
  src/main/java/com/ssginc/showpinglive/util/UserSession.java
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/css/webrtc/kurento.css
  src/main/resources/static/img/background.png
  src/main/resources/static/img/kurento.png
  src/main/resources/static/img/naevatec.png
  src/main/resources/static/img/pipeline.png
  src/main/resources/static/img/show-ping.png
  src/main/resources/static/img/spinner.gif
  src/main/resources/static/img/transparent-1px.png
  src/main/resources/static/img/urjc.gif
  src/main/resources/static/img/webrtc.png
  src/main/resources/static/js/chat/chatRoom.js
  src/main/resources/static/js/stream.js
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/webrtc/webrtc.html
  src/test/java/com/ssginc/showpinglive/chat/MongoDbConnectionTest.java
Labels: feature

#23 Feat: VOD HLS 스트리밍 구현
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/service/StreamService.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/resources/static/js/vod.js
  src/main/resources/templates/watch/vod.html
Labels: feature

#33 Feat: 시청내역 추가.조회 JWT 연동하여 구현
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/controller/AuthController.java
  src/main/java/com/ssginc/showpinglive/controller/MemberController.java
  src/main/java/com/ssginc/showpinglive/controller/WatchController.java
  src/main/java/com/ssginc/showpinglive/dto/request/WatchRequestDto.java
  src/main/java/com/ssginc/showpinglive/repository/WatchRepository.java
  src/main/java/com/ssginc/showpinglive/service/AuthService.java
  src/main/java/com/ssginc/showpinglive/service/MemberService.java
  src/main/java/com/ssginc/showpinglive/service/implement/AuthServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/MemberServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/WatchServiceImpl.java
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/watch/vod.html
Labels: feature

#39 Refactor: 채팅 코드 리팩토링
  build.gradle
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketChatConfig.java
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/dto/object/ChatDto.java
  src/main/java/com/ssginc/showpinglive/handler/WebSocketChatHandler.java
  src/main/java/com/ssginc/showpinglive/service/ChatService.java
  src/main/java/com/ssginc/showpinglive/service/ForbiddenWordFilterService.java
  src/main/java/com/ssginc/showpinglive/service/KafkaConsumerService.java
  src/main/java/com/ssginc/showpinglive/service/KafkaProducerService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ChatServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/ForbiddenWordFilterServiceImpl.java
  src/main/resources/static/css/chat/chat.css
  src/main/resources/static/js/chat/chatRoom.js
  src/main/resources/templates/chat/chatRoom.html
Labels: feature

#44 Refactor: kafka service 분리
  src/main/java/com/ssginc/showpinglive/service/KafkaConsumerService.java
  src/main/java/com/ssginc/showpinglive/service/KafkaProducerService.java
  src/main/java/com/ssginc/showpinglive/service/implement/KafkaConsumerServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/KafkaProducerServiceImpl.java
Labels: refactoring

#41 Feat: VOD 자막기능 구현
  src/main/java/com/ssginc/showpinglive/api/Segments.java
  src/main/java/com/ssginc/showpinglive/api/StorageLoader.java
  src/main/java/com/ssginc/showpinglive/api/SubtitleGenerator.java
  src/main/java/com/ssginc/showpinglive/api/Words.java
  src/main/java/com/ssginc/showpinglive/config/NCPConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketConfig.java
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/controller/WatchController.java
  src/main/java/com/ssginc/showpinglive/handler/LiveHandler.java
  src/main/java/com/ssginc/showpinglive/handler/RecordHandler.java
  src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java
  src/main/java/com/ssginc/showpinglive/repository/WatchRepository.java
  src/main/java/com/ssginc/showpinglive/service/StreamService.java
  src/main/java/com/ssginc/showpinglive/service/SubtitleService.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/SubtitleServiceImpl.java
  src/main/resources/static/css/watch/vod.css
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/watch/vod.html
Labels: feature

#48 Refactor: 라이브 기능 UI 수정
  src/main/resources/static/css/stream/stream.css
  src/main/resources/static/css/style.css
  src/main/resources/static/css/watch/stream.css
  src/main/resources/static/css/watch/vod.css
  src/main/resources/static/js/stream/list.js
  src/main/resources/templates/watch/vod.html
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
Labels: refactoring

#51 Feat: 채팅방 등록 API 구현
  src/main/java/com/ssginc/showpinglive/controller/ChatRoomController.java
  src/main/java/com/ssginc/showpinglive/dto/response/ChatRoomResponseDto.java
  src/main/java/com/ssginc/showpinglive/service/ChatRoomService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ChatRoomServiceImpl.java
  src/main/resources/static/js/chat/chatRoom.js
Labels: feature

#52 Refactor: 채팅-라이브 리팩토링
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/controller/ChatRoomController.java
  src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java
  src/main/java/com/ssginc/showpinglive/repository/ChatRoomRepository.java
  src/main/java/com/ssginc/showpinglive/service/ChatRoomService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ChatRoomServiceImpl.java
  src/main/resources/static/css/watch/stream.css
  src/main/resources/static/js/chat/chatRoom.js
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/chat/chatRoom.html
  src/main/resources/templates/layout.html
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
Labels: refactoring

#54 Refactor: 채팅 리팩토링
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/service/implement/ChatServiceImpl.java
  src/main/resources/static/js/stream/stream.js
Labels: refactoring

#57 Feat: HLS NCP와 연동하여 구현
  src/main/java/com/ssginc/showpinglive/api/StorageLoader.java
  src/main/java/com/ssginc/showpinglive/controller/HlsController.java
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/service/HlsService.java
  src/main/java/com/ssginc/showpinglive/service/StreamService.java
  src/main/java/com/ssginc/showpinglive/service/implement/HlsServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/resources/static/js/watch/vod.js
  src/test/java/com/ssginc/showpinglive/StreamControllerTest.java
  src/test/java/com/ssginc/showpinglive/hls/HlsServiceTest.java
Labels: feature

#60 Feat: 신고 관리 페이지네이션, sorting, 상세정보, TDD
  build.gradle
  src/main/java/com/ssginc/showpinglive/controller/ReportController.java
  src/main/java/com/ssginc/showpinglive/dto/object/ReportDto.java
  src/main/java/com/ssginc/showpinglive/dto/response/ReportResponseDto.java
  src/main/java/com/ssginc/showpinglive/repository/ReportRepository.java
  src/main/java/com/ssginc/showpinglive/service/ReportService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ReportServiceImpl.java
  src/main/resources/static/css/report/report.css
  src/main/resources/static/js/report/report.js
  src/main/resources/templates/report/report.html
  src/test/java/com/ssginc/showpinglive/chat/ChatMessageIntegrationTest.java
  src/test/java/com/ssginc/showpinglive/chat/CreateChatRoomTest.java
  src/test/java/com/ssginc/showpinglive/chat/MongoDbConnectionTest.java
Labels: feature

#61 Integration: 라이브 송출 ~ 종료 과정 통합
  src/main/java/com/ssginc/showpinglive/config/WebSocketConfig.java
  src/main/java/com/ssginc/showpinglive/handler/LiveHandler.java
  src/main/java/com/ssginc/showpinglive/handler/WebSocketChatHandler.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/resources/static/js/stream/stream.js
Labels: refactoring

#64 Refactor: 시청 측 로직 리팩토링
  src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java
  src/main/resources/static/css/watch/stream.css
  src/main/resources/static/js/stream/list.js
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/layout.html
  src/main/resources/templates/webrtc/watch.html
Labels: refactoring

#66 Refactor: 신고 관리 상세정보 리팩토링
  src/main/java/com/ssginc/showpinglive/controller/ReportController.java
  src/main/java/com/ssginc/showpinglive/dto/response/ReportResponseDto.java
  src/main/java/com/ssginc/showpinglive/service/implement/ReportServiceImpl.java
  src/main/resources/static/js/report/report.js
  src/main/resources/templates/report/report.html
Labels: refactoring

#74 Refactor: 프로젝트 리팩토링
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/controller/WatchController.java
  src/main/java/com/ssginc/showpinglive/handler/RecordHandler.java
  src/main/java/com/ssginc/showpinglive/jwt/JwtFilter.java
  src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java
  src/main/resources/static/css/watch/stream.css
  src/main/resources/static/js/stream/stream.js
  src/main/resources/static/js/watch/history.js
  src/main/resources/templates/layout.html
  src/main/resources/templates/watch/history.html
Labels: refactoring

#76 Refactor: 채팅 신고 등록
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/controller/ReportController.java
  src/main/java/com/ssginc/showpinglive/dto/request/ReportRegisterRequestDto.java
  src/main/java/com/ssginc/showpinglive/service/ReportService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ReportServiceImpl.java
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/webrtc/webrtc.html
Labels: refactoring

#79 Refactor : 채팅 금칙어 리팩토링
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketAuthInterceptorConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketChatConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebsocketUserInterceptorConfig.java
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/handler/UserCustomHandshakeHandler.java
  src/main/java/com/ssginc/showpinglive/jwt/JwtFilter.java
  src/main/java/com/ssginc/showpinglive/repository/ForbiddenWordRepository.java
  src/main/resources/static/js/report/report.js
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/report/report.html
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
Labels: refactoring

#80 Feat: 성능테스트 시나리오 구현
  src/main/java/com/ssginc/showpinglive/controller/HlsController.java
  src/main/java/com/ssginc/showpinglive/service/HlsService.java
  src/main/java/com/ssginc/showpinglive/service/implement/HlsServiceImpl.java
Labels: feature

#82 Refactor: 채팅방 권한별 에러 수정
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/dto/object/ChatDto.java
  src/main/java/com/ssginc/showpinglive/service/ChatService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ChatServiceImpl.java
  src/main/resources/static/js/stream/stream.js
  src/test/java/com/ssginc/showpinglive/chat/ChatMessageIntegrationTest.java
Labels: refactoring

#83 Feat: 라이브 시청 UI 및 상품 정보 조회 구현
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java
  src/main/java/com/ssginc/showpinglive/dto/response/GetStreamProductInfoResponseDto.java
  src/main/java/com/ssginc/showpinglive/service/StreamService.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/resources/static/css/watch/stream.css
  src/main/resources/static/js/stream/get_stream_info.js
  src/main/resources/static/js/stream/register_stream.js
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
Labels: feature

#85 Fix: 라이브 시청 버그 수정
  src/main/resources/static/js/stream/stream.js
  src/main/resources/static/js/stream/watch.js
  src/main/resources/templates/webrtc/watch.html
Labels: bug, refactoring

#88 Refactor: 회원관리 서비스 클래스 인터페이스로 리팩토링
  build.gradle
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/controller/AdminController.java
  src/main/java/com/ssginc/showpinglive/controller/AuthController.java
  src/main/java/com/ssginc/showpinglive/entity/Member.java
  src/main/java/com/ssginc/showpinglive/entity/SocialMember.java
  src/main/java/com/ssginc/showpinglive/entity/SocialType.java
  src/main/java/com/ssginc/showpinglive/jwt/JwtFilter.java
  src/main/java/com/ssginc/showpinglive/jwt/JwtUtil.java
  src/main/java/com/ssginc/showpinglive/repository/MemberRepository.java
  src/main/java/com/ssginc/showpinglive/service/AdminAccountService.java
  src/main/java/com/ssginc/showpinglive/service/MailService.java
  src/main/java/com/ssginc/showpinglive/service/RedisTestService.java
  src/main/java/com/ssginc/showpinglive/service/RefreshTokenService.java
  src/main/java/com/ssginc/showpinglive/service/implement/AdminAccountServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/MailServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/RedisTestServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/RefreshTokenServiceImpl.java
  src/main/resources/static/js/login/jwt.js
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/login/logout.js
  src/main/resources/static/js/login/signup.js
  src/main/resources/static/js/login/totp-setup.js
  src/main/resources/templates/login/login.html
Labels: refactoring

#93 Refactor: 라이브 코드 리팩토링
  src/main/resources/static/js/stream/get_stream_info.js
  src/main/resources/static/js/stream/list.js
  src/main/resources/static/js/stream/product_modal.js
  src/main/resources/static/js/stream/register_stream.js
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/webrtc/watch.html
Labels: refactoring

#94 Refactor: 비로그인, 공지, 채팅신고 리팩토링
  src/main/java/com/ssginc/showpinglive/controller/WebRtcController.java
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
Labels: refactoring

#95 Refactor: VOD 관련 리팩토링
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/controller/WatchController.java
  src/main/java/com/ssginc/showpinglive/dto/request/WatchRequestDto.java
  src/main/java/com/ssginc/showpinglive/service/WatchService.java
  src/main/java/com/ssginc/showpinglive/service/implement/WatchServiceImpl.java
  src/main/resources/static/css/stream/stream.css
  src/main/resources/static/css/watch/history.css
  src/main/resources/static/js/stream/list.js
  src/main/resources/static/js/watch/history.js
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/watch/history.html
  src/main/resources/templates/watch/vod.html
Labels: refactoring

#104 Feat: 배치작업 구현
  build.gradle
  src/main/java/com/ssginc/showpinglive/api/StorageLoader.java
  src/main/java/com/ssginc/showpinglive/config/BatchConfig.java
  src/main/java/com/ssginc/showpinglive/controller/BatchController.java
  src/main/java/com/ssginc/showpinglive/controller/HlsController.java
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/dto/request/FileRequestDto.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/java/com/ssginc/showpinglive/service/implement/SubtitleServiceImpl.java
  src/main/resources/static/js/stream/stream.js
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/watch/vod.html
Labels: feature

#110 Feat: 라이브 메인페이지 수정
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/dto/response/StreamResponseDto.java
  src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java
  src/main/java/com/ssginc/showpinglive/service/StreamService.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
  src/main/resources/static/css/stream/stream.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/stream/list.js
  src/main/resources/templates/layout.html
  src/main/resources/templates/stream/list.html
Labels: feature

#112 Refactor : 채팅 UI, FAQ
  src/main/resources/static/css/watch/stream.css
  src/main/resources/static/js/stream/stream.js
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
Labels: refactoring

#115 Feat: 메인페이지 VOD API 구현
  src/main/java/com/ssginc/showpinglive/controller/StreamController.java
  src/main/java/com/ssginc/showpinglive/repository/StreamRepository.java
  src/main/java/com/ssginc/showpinglive/service/StreamService.java
  src/main/java/com/ssginc/showpinglive/service/implement/StreamServiceImpl.java
Labels: feature

#127 Feat: 관리자모드 네비바 설정 구현
  src/main/java/com/ssginc/showpinglive/controller/MemberController.java
  src/main/resources/static/js/scripts.js
  src/main/resources/templates/layout.html
Labels: feature

#128 Feat: VOD 채팅 확인 기능
  src/main/java/com/ssginc/showpinglive/config/SecurityConfig.java
  src/main/java/com/ssginc/showpinglive/controller/ChatController.java
  src/main/java/com/ssginc/showpinglive/dto/object/ChatDto.java
  src/main/java/com/ssginc/showpinglive/repository/ChatRepository.java
  src/main/java/com/ssginc/showpinglive/service/ChatService.java
  src/main/java/com/ssginc/showpinglive/service/implement/ChatServiceImpl.java
  src/main/resources/static/js/stream/stream.js
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/watch/vod.html
  src/main/resources/templates/webrtc/watch.html
  src/main/resources/templates/webrtc/webrtc.html
  src/test/java/com/ssginc/showpinglive/chat/ChatMessageIntegrationTest.java
Labels: feature

#129 Feat: vod 상품 UI 구현 #119
  src/main/java/com/ssginc/showpinglive/controller/WatchController.java
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/watch/vod.html
Labels: feature

#132 Refactor: 신고 관리 리팩토링
  src/main/java/com/ssginc/showpinglive/controller/ReportController.java
  src/main/java/com/ssginc/showpinglive/dto/response/ReportResponseDto.java
  src/main/resources/static/css/report/report.css
  src/main/resources/static/js/report/report.js
  src/main/resources/templates/report/report.html
Labels: refactoring

#136 Feat: 레이아웃 네비바 수정
  src/main/resources/static/img/icon/order.png
  src/main/resources/templates/layout.html
Labels: feature, refactoring

#138 Hotfix: 웹소켓 버그 수정
  src/main/resources/static/js/stream/stream.js
Labels: refactoring

#139 Fix: 파일명 형식 수정
  src/main/resources/static/js/stream/stream.js
Labels: refactoring

#142 Refactor/live vod chat/140
  src/main/java/com/ssginc/showpinglive/config/WebSocketAuthInterceptorConfig.java
  src/main/java/com/ssginc/showpinglive/config/WebSocketConfig.java
  src/main/java/com/ssginc/showpinglive/controller/ChatRoomController.java
  src/main/java/com/ssginc/showpinglive/handler/UserCustomHandshakeHandler.java
  src/main/java/com/ssginc/showpinglive/handler/WebSocketChatHandler.java
  src/main/java/com/ssginc/showpinglive/service/implement/ForbiddenWordFilterServiceImpl.java
  src/main/resources/static/css/index.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/watch/vod.js
  src/main/resources/templates/index.html
  src/main/resources/templates/watch/vod.html
Labels: refactoring
